before_commands:
    - "composer update --prefer-source"

tools:
    external_code_coverage: true
    php_code_coverage: true
    php_code_sniffer:
        enabled: true
        config:
            standard: PSR2
        filter:
            paths: ["src/*", "spec/*"]
    php_cpd:
        enabled: true
        excluded_dirs: ["build", "docs", "spec", "vendor"]
    php_cs_fixer:
        enabled: true
        config:
            level: all
        filter:
            paths: ["src/*", "spec/*"]
    php_loc:
        enabled: true
        excluded_dirs: ["build", "docs", "spec", "vendor"]
    php_mess_detector:
        enabled: true
        filter:
            paths: ["src/*"]
    php_pdepend:
        enabled: true
        excluded_dirs: ["build", "docs", "spec", "vendor"]
    php_analyzer: true
    php_analyzer:
        filter:
            paths: ["src/*", "spec/*"]
sensiolabs_security_checker: true
